{{- range $elem := .Values.pages }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: my-configmap-{{ $elem }}
  namespace : padawan
data:
  page-{{ $elem }}.html: |-
    <html>
      <h1>Welcome to Helm templating</h1>
      </br>
      <h1><p>This is configmap/deployment {{ $elem }}</p></h1>
    </html>
---
{{- end }}
